{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}伽利略卫星导航计划成功进行三维定位验证</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: justify">2013年3月12日，伽利略卫星导航计划，利用此前在轨的4颗卫星及地面设施进行了三维定位试验，并取得了预期结果。</P>
<P style="TEXT-ALIGN: justify"><BR>　 三维定位验证（经度、纬度、高度）至少需要来自4颗卫星的定位信号。Galileo于2011年和2012年分别发射2颗运营卫星，构成一个四星小星座。此次三维定位实验在荷兰的欧空局实验室进行，精度为10-15米。定位试验完全利用欧洲空间基础设施、欧洲在轨卫星、位于德国和意大利的两个控制中心以及遍布欧洲的地面设施网络。</P>
<P style="TEXT-ALIGN: justify"><BR>　&nbsp; 欧盟认为，此举标志着伽利略卫星导航计划跨越了历史性和技术性两个里程碑。从历史上看，这是欧洲首次利用自主独立的导航系统进行的定位实验。从技术上看，卫星导航信号的生成，是开展系统全面验证，在年底前进行星座全面布置的重要一步。</P>
<P style="TEXT-ALIGN: justify"><BR>　 目前Galileo有4颗卫星，每天只有2-3个小时可接收到完整的导航信号。随着更多卫星的加入以及更多地面设施的上线，接收完整导航信号的时间将越来越长。未来数月，伽利略将进一步优化导航信号，确定伽利略系统时间与协调通用时间的偏差，以提供可靠、精准的授时服务，并且确定与GPS时间的偏差，确保与GPS系统兼容。按照实施计划，Galileo将于2014年底，提供初始导航服务。</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://www.most.gov.cn/gnwkjdt/201304/t20130423_101037.htm">http://www.most.gov.cn/gnwkjdt/201304/t20130423_101037.htm</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='litpic'}{/dede:field}
