{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}爱尔兰地学数据集成（GeoDI）项目介绍</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: justify">在过去的数年中，海洋所及其合作者通过目前爱尔兰可持续发展的综合测绘项目和以前爱尔兰国家海底调查及欧洲海底栖息地调查项目收集了大量的地学数据。</P>
<P style="TEXT-ALIGN: justify"><STRONG>1项目介绍</STRONG></P>
<P style="TEXT-ALIGN: justify"><STRONG>1.1 解决的问题</STRONG></P>
<P style="TEXT-ALIGN: justify">项目要解决的关键问题在于通过整合地理数据和其他数据资源，如生物学、化学和环境的数据，以形成昂贵和有价值的产品，并从中获得最大利益。这将允许运用生态系统方法分析海洋和地理数据，形成一个全面和更复杂的海洋环境变化观点，从而提高科学建议的质量。</P>
<P style="TEXT-ALIGN: center"><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/201304/W020130402547808260850.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130311330373103533.jpg" OLDSRC=W020130402547808260850.jpg></P>
<P style="TEXT-ALIGN: justify"><BR clear=all><STRONG>1.2 目标</STRONG></P>
<P style="TEXT-ALIGN: justify">地学数据集成(<A class=" FCK__AnchorC" name=OLE_LINK6>GeoDI</A>)项目目标是通过检验爱尔兰海洋地理数据集集成中的关键问题和利用评价工具及服务，强化管理，获取并分析地学数据，来应对这一挑战。GeoDI项目的具体目标如下：</P>
<P style="TEXT-ALIGN: justify">（1）检查海洋所及其合作者拥有的地学数据集，包括分析与其他数据集的集成和评价其意义。</P>
<P style="TEXT-ALIGN: justify">（2）回顾国际海洋地球科学数据管理的最佳实践。</P>
<P style="TEXT-ALIGN: justify">（3）为所选择的地学数据集，选择合适的数据模型，使数据能够与其他海洋所拥有的数据库集成，或者与最新的生物数据集成项目中的生物数据库集成。</P>
<P style="TEXT-ALIGN: justify">（4）发展地学资源实体论。</P>
<P style="TEXT-ALIGN: justify">①提供一个地学知识库，可以通过语义网络实现共享、循环使用、查询；</P>
<P style="TEXT-ALIGN: justify">②通过发展元数据实例属性的本体术语，提高元数据的互操作性。</P>
<P style="TEXT-ALIGN: justify">（5）基于已确定的语义映射，定义数据转换和加载程序。</P>
<P style="TEXT-ALIGN: justify">（6）指定自动化过程，使生成的元数据，足以让用户能够成功地识别、定位和分析。</P>
<P style="TEXT-ALIGN: justify">（7）为数据的传播和集成分析，指定适当的数据输出和传播方法。</P>
<P style="TEXT-ALIGN: justify">（8）识别过程变化，提高数据管理。</P>
<P style="TEXT-ALIGN: justify">（9）为测试模型实施，数据加载和检索，实现一个原型数据的存储和检索系统。</P>
<P style="TEXT-ALIGN: justify">（10）评估海洋所内部或者通过集成得到的地球物理数据/地质数据的潜在分析和服务。</P>
<P style="TEXT-ALIGN: justify">（11）评估促进地理空间分析与地球物理、地质数据查询的工具和方法/流程。</P>
<P style="TEXT-ALIGN: center"><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/201304/W020130402547808637827.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130311330600075865.jpg" OLDSRC=W020130402547808637827.jpg></P>
<P style="TEXT-ALIGN: justify"><BR clear=all><STRONG>1.3 知识产权</STRONG></P>
<P style="TEXT-ALIGN: justify"><A class=" FCK__AnchorC" name=OLE_LINK16><SPAN>GeoDI</SPAN></A>项目的所有产出都是可以免费获得。项目合作者撰写的说明书和最佳实践报告在GeoDI网站上可以获得。海洋生物群落的研究成果可以被用于商业和非商业目的。科克大学开发的软件，通过许可机制，用于非商业用途，能够免费获得软件，例如语义网络服务，目录服务中介，数据抽取、转换和加载工具。</P> 
<P align=left><STRONG>2&nbsp;</STRONG><A class=" FCK__AnchorC" name=OLE_LINK13><STRONG>GeoDI</STRONG></A><STRONG>项目的主要成果</STRONG></P>
<P>（1）一组审查现有的技术、标准、模型的报告和关于集成、管理及地学数据集传送的最佳实践。</P>
<P>（2）一个基于弧形海洋的可集成、可扩展的地学数据模型，与现存的海洋研究所数据库相匹配。</P>
<P>（3）基于现有行之有效的词汇表，建立的一组使用在数据、元数据、转换、加载的地学本体论。</P>
<P>（4）一个关于地学数据资源的集成、管理、传递的完整系统规范，包括子系统的详细规范和它们之间如何地组合在一起及相互作用。</P>
<P>（5）一个半自动、通用、基于本体的抽取、转换和下载工具，向综合地学数据库中加载数据，它可以进一步开发和定制其它系统和数据库。</P>
<P>（6）综合地学信息系统，是一个数据集成、管理和访问地学数据资源的完整系统。除了标准服务以外，综合地学信息系统还包括以下可以被重复使用的功能：</P>
<P>访问地学领域本体的语义化网络服务。<A class=" FCK__AnchorC" name=OLE_LINK18>该服务是在</A>JAVA中开发的，利用了应用编程接口，<A class=" FCK__AnchorC" name=OLE_LINK20><SPAN>公开</A>网站是</SPAN>http://gdo.ucc.ie:8080/gdo/SWS。</P>
<P>一个目录服务的中介允许访问分布式目录服务，解决它们之间的语义化冲突。该服务是在JAVA中开发的，公开网站是http://gdo.ucc.ie:8080/gdo/CS。</P>
<P>地学数据在线门户网站，是在Adobe Flex 3中开发的，网站地址是http://gdo.ucc.ie。</P>
<P>（7）一份建议报告，评估潜在的分析和服务，识别促进地球科学数据空间分析的工具和方法。</P>
<P>（8）<A class=" FCK__AnchorC" name=OLE_LINK116>3</A><SPAN>份出版物</SPAN>。</P>
<P>在2010年的摄影测量与遥感学会年度会议上，发表了题为《基于自动抽取、转换和加载海洋地理数据的本体论》的论文。</P>
<P>在2009年的欧洲和拉丁美洲的地理科学网络设施会议上，提交了题为《G2图书馆：一个网络地学图书馆》的报告，该报告介绍了一个网络图书馆，在网络中管理、发现和访问大型海洋地球科学数据库。</P>
<P>出版了一本题为《沿海信息学——网络地图集的设计与实现》的专著。</P>
<P align=left><STRONG>3 影响和效益</STRONG></P>
<P><A class=" FCK__AnchorC" name=OLE_LINK50><SPAN>GeoDI</SPAN></A><SPAN><SPAN>项目</SPAN></SPAN>考虑了增加专家评价，增加了地学数据集成领域的内部和外部能力建设。它也为本体论、人工智能、面向服务的体系结构及地理数据集成、管理和访问的网络计算的创新应用，提供了机会。该项目使得专业知识在爱尔兰和美国、个体合作机构与个体之间转移。GeoDI项目跨学科成功的进行了地学数据管理（地球科学、数据库管理和人工智能）。</P>
<P><A class=" FCK__AnchorC" name=OLE_LINK33>GeoDI</A><SPAN>项目</SPAN>对于所有的合作者参与其他相关项目提供了一个机会，特别是<A class=" FCK__AnchorC" name=OLE_LINK28>格里菲斯的测绘学</A>-地球科学，加入数据连接起来思考，和欧盟的FP7 NETMAR项目。</P>
<P><A class=" FCK__AnchorC" name=OLE_LINK35>GeoDI</A>项目允许规范和发展一个已经被NETMAR项目采用的语义框架，并且进一步优化和提交一个标准准则，为访问语义资源提供了一个标准。</P>
<P>根据美国地质调查局(<A class=" FCK__AnchorC" name=OLE_LINK93>USGS</A>)的Brian Andrews介绍，<A class=" FCK__AnchorC" name=OLE_LINK39>GeoDI</A>项目描述的交付结果，对于任何大型海洋地球物理映射<A class=" FCK__AnchorC" name=OLE_LINK37>项目</A>和同样规模的数据管理和传播项目的国际组织，都是一个非常宝贵的资源，在整个GeoDI项目中，他都分享结果和他的同事在USGS<A class=" FCK__AnchorC" name=OLE_LINK41>沿海和海洋地质项目</A>及知识管理工作组中。<A class=" FCK__AnchorC" name=OLE_LINK43>GeoDI</A>项目的全部方法是来自多学科项目合作者。他鼓励USGS沿海和海洋地质项目以GeoDI项目为模板，并启动一个类似项目。虽然他没有后续研究的明确计划，他将继续使用提交的成果作为参考，促进GeoDI项目作为一个优秀的例子，整个项目包括成功管理和交付海洋地球物理数据到一个国际用户的所有重要步骤。</P>
<P>Brian Andrews特别强调了回顾本体和受控词汇表及识别标准和模型是USGS的特殊使用。他得出结论：获得了一个对组织的新认识和项目的组织方法。USGS的工作具有相同的数据类型和数据量，但是不具有相似的方式，因为数据遍布美国和国际水域。不过我们可以采用类似的数据模型作为一种机制来集中和管理我们的类似数据集。另外，说明了大量有关控制词汇表、粒状或分层元数据和本体的重要性。</P>
<P style="TEXT-ALIGN: justify">原文题目：</P>
<P style="TEXT-ALIGN: justify">GeoDI - Geoscientific Data Integration</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://oar.marine.ie/bitstream/10793/851/1/GeoDI%20Geoscientific%20Data%20Integration.pdf">http://oar.marine.ie/bitstream/10793/851/1/GeoDI%20Geoscientific%20Data%20Integration.pdf</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='litpic'}{/dede:field}
