{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}日本开建国产导航系统 三颗卫星即可覆盖全境</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: center"><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/201304/W020130423494247165993.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130423493984254752.jpg" OLDSRC=W020130423494247165993.jpg></P>
<P style="TEXT-ALIGN: center"><STRONG>日本所计划建造的准天顶卫星导航系统只需要一颗地球同步卫星和两颗准天顶卫星即可形成对本土的全时覆盖，非常节省开支</STRONG></P>
<P style="TEXT-ALIGN: justify">2013年3月29日，日本内务省宣布，分别与三菱电机公司和日本电气公司（NEC）签订合同。这两家公司将为日本的“准天顶”卫星系统（QZSS）建造卫星和地面控制系统。</P>
<P style="TEXT-ALIGN: justify">三菱电机公司所签订合同价值500亿日元（5400万美元）。根据合同规定，该公司将建造1颗地球同步卫星和2颗“准天顶”卫星，与2010年9月11日发射的第一颗“准天顶”卫星“指路”号构建卫星星座。</P>
<P style="TEXT-ALIGN: justify">与此同时，NEC将领导建立一个团队，成员由三菱UFJ租赁有限公司和三菱电机公司组成。该团队将利用民间投资建造“准天顶”地面控制段。目前，预计将从民间融资渠道募集到约1170亿日元（13亿美元）的资金，用于地面系统的设计和建造，并支持该系统未来15年的运行。</P>
<P style="TEXT-ALIGN: justify">每一颗“准天顶”卫星都将传送以下信号：L1 C/A，L1C，L2C，L5，L1S（之前被称为L1-SAIF，即L1-完整功能亚米级增强），L6a（一种公共规范服务），L5S（GPS L5频率的增强信号），以及L6b（之前被称为LEX，L波段试验，一种高精度增强信号，频率中心1278.75MHz，与“伽利略”E6信号相同）。根据计划，“准天顶”系统将在2018年3月完成在轨测试。</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://www.dzwww.com/xinwen/guojixinwen/201304/t20130404_8195349.htm">http://www.dzwww.com/xinwen/guojixinwen/201304/t20130404_8195349.htm</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
