<?php
$z[0]=Array("item","",4,82);
$z[0][4]['name']="插件管理器";
$z[0][4]['link']="plus_main.php";
$z[0][4]['rank']="10";
$z[0][4]['target']="main";
$z[1]=Array("item","",86,188);
$z[1][4]['name']="友情链接";
$z[1][4]['link']="friendlink_main.php";
$z[1][4]['rank']="plus_友情链接模块";
$z[1][4]['target']="main";
$z[2]=Array("item","",190,280);
$z[2][4]['name']="投票模块";
$z[2][4]['link']="vote_main.php";
$z[2][4]['rank']="plus_投票模块";
$z[2][4]['target']="main";

?>