{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}我国成功发射首颗高分辨率对地观测系统卫星</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P align=center>&nbsp;<IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/201304/W020130428276941381268.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130428275534215672.jpg" OLDSRC=W020130428276941381268.jpg></P>
<P style="TEXT-ALIGN: center"><STRONG>图为发射前夕，“高分一号”卫星与运载火箭在发射塔架进行对接。梁杰 摄</STRONG></P>
<P style="TEXT-ALIGN: justify">中国国家科技重大专项高分辨率对地观测系统首颗卫星“高分一号”4月26日中午在酒泉卫星发射中心成功发射，同时还成功搭载发射了两个荷兰卫星分配器和三颗分别由厄瓜多尔、阿根廷和土耳其研制的小卫星。</P>
<P style="TEXT-ALIGN: justify">北京时间26日12时13分，中国“长征二号丁”运载火箭在酒泉卫星发射中心发射场顺利点火升空，以“一箭多星”发式将“高分一号”及搭载的卫星分配器和小卫星成功送入预定轨道。</P>
<P style="TEXT-ALIGN: justify">“高分一号”卫星由中国航天科技集团公司所属中国空间技术研究院航天东方红卫星有限公司研制，卫星突破了高空间分辨率、多光谱与宽覆盖相结合的光学遥感等关键技术，设计寿命5至8年。卫星主要用户为中国国土资源部、农业部和环境保护部。</P>
<P style="TEXT-ALIGN: justify">高分辨率对地观测系统工程是中国《国家中长期科学和技术发展规划纲要(2006-2020)年》确定的16个重大专项之一，由天基观测系统、临近空间观测系统、航空观测系统、地面系统、应用系统等组成，计划“十二五”期间发射5至6颗观测卫星，目标是建成高空间分辨率、高时间分辨率、高光谱分辨率的对地观测系统，并与其他观测手段相结合，到2020年形成具有时空协调、全天时、全天候、全球范围观测能力的稳定运行系统。</P>
<P style="TEXT-ALIGN: justify">航天专家表示，高分辨率对地观测系统国家科技重大专项的实施，将全面提升中国自主获取高分辨率观测数据能力，推动卫星及应用技术的跨越发展，保障现代农业、防灾减灾、资源环境、国家安全等重大战略需求，支撑国土调查与利用、地理测绘、海洋和气候气象观测、水利和林业资源监测、城市和交通精细化管理、疫情评估与公共卫生应急、地球系统科学研究等重点领域应用需求，加快推动中国空间信息产业发展。</P>
<P style="TEXT-ALIGN: justify">承担本次卫星发射任务的“长征二号丁”运载火箭由中国航天科技集团公司所属上海航天技术研究院研制。这是中国2013年度首次航天发射，也是中国“长征”系列运载火箭第175次航天飞行。</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://news.sciencenet.cn/htmlnews/2013/4/277272.shtm">http://news.sciencenet.cn/htmlnews/2013/4/277272.shtm</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='litpic'}{/dede:field}
