<?php
$z[0]=Array("field","遥感与数字地球、数字地",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机",76,364);
$z[1][4]['name']="description";
$z[2]=Array("field","日本计划发射卫星监视全球海洋</strong>",366,455);
$z[2][4]['name']="title";
$z[3]=Array("field","",457,496);
$z[3][4]['name']="writer";
$z[4]=Array("field","",498,537);
$z[4][4]['name']="source";
$z[5]=Array("field","<DIV class=cas_content>\n<P style=\"TEXT-ALIGN: justify\">2013年7月7日，据《日本产业新闻》报道，日本内阁府（Cabinet Office）计划今后5年陆续发射9颗专用卫星，用于对日本海域附近船只通行的所有航路进行严密监视。它们还可以收集数据来预测海啸等自然灾害。</P>\n<P style=\"TEXT-ALIGN: justify\">日本现有的卫星系统每天只能工作不超过8小时。此次计划发射的新兴卫星属于热辐射检测卫星，可以在夜间工作。每颗卫星造价约200亿日元。卫星发射以后，日本将及时辨认国外船只。日本还计划将监测数据和分析技术向南亚国家出售。</P>\n<P style=\"TEXT-ALIGN: justify\">&nbsp;</P>\n<P style=\"TEXT-ALIGN: justify\">原文题目：Japan to launch satellites to monitor oceans</P>\n<P style=\"TEXT-ALIGN: justify\">来源：</P>\n<P style=\"TEXT-ALIGN: justify\"><A href=\"http://www.enca.com/technology/japanese-satellites-monitor-oceans\">http://www.enca.com/technology/japanese-satellites-monitor-oceans</A> </P>\n<P style=\"TEXT-ALIGN: justify\">",539,1651);
$z[5][4]['name']="body";
$z[6]=Array("field","",1653,1693);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1695,1734);
$z[7][4]['name']="litpic";

?>