{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}日本计划发射卫星监视全球海洋</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: justify">2013年7月7日，据《日本产业新闻》报道，日本内阁府（Cabinet Office）计划今后5年陆续发射9颗专用卫星，用于对日本海域附近船只通行的所有航路进行严密监视。它们还可以收集数据来预测海啸等自然灾害。</P>
<P style="TEXT-ALIGN: justify">日本现有的卫星系统每天只能工作不超过8小时。此次计划发射的新兴卫星属于热辐射检测卫星，可以在夜间工作。每颗卫星造价约200亿日元。卫星发射以后，日本将及时辨认国外船只。日本还计划将监测数据和分析技术向南亚国家出售。</P>
<P style="TEXT-ALIGN: justify">&nbsp;</P>
<P style="TEXT-ALIGN: justify">原文题目：Japan to launch satellites to monitor oceans</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://www.enca.com/technology/japanese-satellites-monitor-oceans">http://www.enca.com/technology/japanese-satellites-monitor-oceans</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
