{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}卫星图像协克立金融合技术能有效提高地理数据的分析</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: justify">美国地理学家协会2013年年会（Association of&nbsp;American Geographers Annual Meeting）4月9-13日在洛杉矶举行，这是美国地理界一年一度的盛会，来自世界各地7000多名科学家参加了这个跨学的会议，研讨与地理学相关的科学研究。辛辛那提大学研究生Bo Yang在会议上介绍了他的研究成果，北阿拉斯加热融湖（thaw lake）地表温度的多传感器时空图像<A class=" FCK__AnchorC" name=OLE_LINK9>协克立金</A>方法（<A class=" FCK__AnchorC" name=OLE_LINK7>Cokriging</A>）融合研究。</P>
<P style="TEXT-ALIGN: justify">Yang的数据来自于两种不同类型的极轨卫星系统。他用Cokriging的空间统计技术融合高时间分辨率与高空间分辨率影像反演土地表面温度，可以简化传统图像融合的复杂与费时。</P>
<P style="TEXT-ALIGN: justify">他的这种算法可以弥补两个数据集之间的时空差距，从而获得一个错综复杂的详细地图，覆盖很大的表面积，使得地理学家能够迅速获得每天甚至每小时地表温度与辐射信息。这些环境参数对农业和水资源管理非常重要，可以用来检测干旱的发生和严重程度。</P>
<P style="TEXT-ALIGN: justify">原文题目：Satellite Sandwich Technique Improves Analysis of Geographical Data</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://www.uc.edu/news/NR.aspx?id=17542">http://www.uc.edu/news/NR.aspx?id=17542</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
