{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}新证据支持二氧化碳导致气温升高</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P>欧洲研究团队日前报告说，他们对南极冰芯样本进行研究后发现，在末次冰消期，南极气温上升与大气中二氧化碳浓度增加同步发生。这一发现表明，二氧化碳极有可能是这一时期南极气候变暖的原因之一。</P>
<P>冰消期指从盛冰期冰川开始消融退缩至冰川消亡这一时段。此前研究曾认为，在距今约2万至1万年前的末次冰消期，南极大气中二氧化碳浓度在气温上升800年后才开始增加。南极冰盖保存了丰富的古代大气和气温资料，可供人们研究二氧化碳浓度与气温变化的时间顺序，进而了解二氧化碳及其引发的温室效应与气候变化之间的关系。</P>
<P>一支由法国研究人员领导的欧洲研究团队对5块南极冰芯样本进行了分析。由于冰芯封闭的气泡内气体的年龄与冰芯的年龄存在差异，研究人员通过测量气体中氮15同位素含量等方法来确定气泡和冰芯的年代差，由此发现，在末次冰消期南极二氧化碳浓度与气温是同步变化。</P>
<P>研究人员下一步打算对同时期的其他冰芯进行分析，并研究其他时期南极二氧化碳浓度与气温变化的时间顺序。相关论文已发表在新一期《科学》杂志上。</P>
<P>来源：</P>
<P><A href="http://www.stdaily.com/stdaily/content/2013-03/04/content_578422.htm">http://www.stdaily.com/stdaily/content/2013-03/04/content_578422.htm</A></P>
<P>{/dede:field}
{dede:field name='litpic'}{/dede:field}
