<h2><a href="[field:arcurl/]">[field:title/]</a></h2>
    <p>[field:info/]...<a href="[field:arcurl/]">[查看全文]</a></p>
    {/dede:arclist

               </div><!--intro end-->
               <div class="list">
                  <ul>

  {dede:arclist titlelen='60' row='8' typeid='22'}
      <li><span><img src="{dede:global.cfg_templets_skin/}/images/dian.png" width="5px" height="5px" alt="" /></span><a href="[field:arcurl /]">[field:title /]</a></li>