{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}印度将造分辨率达0.25米的高分对地观测卫星</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: justify">印度太空研究组织准备建造一颗遥感卫星 Cartosat-3，该卫星对地观测分辨率可达0.25米。</P>
<P style="TEXT-ALIGN: justify">目前，美国数字全球公司GeoEye-1卫星拍摄的对地观测图像是商业卫星图像中分辨率最高的。这颗美国卫星2008年9月发射，可拍摄分辨率0.41米的全色图像。另一颗WorldView-2卫星分辨率为0.46米。然而按照美国规定，可对外发布的商业图像分辨率要劣于0.5米。数字全球公司计划2014年发射WorldView-3卫星，其分辨率0.31米。Cartosat-3卫星照相机分辨率要优于0.31米，其卫星图像能允许分析人员分辨出目标是汽车还是摩托车。</P>
<P style="TEXT-ALIGN: justify">在印度航天部“2013-2014年拨款需求注意事项”中，Cartosat-3作为独立项目分配到200万美元。这份文件是预算文件的一部分，近日已上交国会，文件指出：“Cartosat-3是一颗先进遥感卫星，将用于高分辨率成像和制图应用，分辨率达到0.25米”。</P>
<P style="TEXT-ALIGN: center"><STRONG><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/201304/W020130423493016152927.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130423492829333592.jpg" OLDSRC=W020130423493016152927.jpg></STRONG></P>
<P style="TEXT-ALIGN: center"><STRONG>资料图：印度Cartosat-2遥感卫星表示图</STRONG></P>
<P style="TEXT-ALIGN: justify">印度1988年发射了首颗运行遥感卫星IRS-1A，其上最高分辩率照相机分辨率为36米。7年之后IRS-1C卫星发射，其上制图照相机分辨率5.8米。在美国“伊科诺斯”（Ikonos）卫星1988年发射之前，IRS-1C曾一直是世界上分辨率最高的民用卫星。印度2011年发射技术试验卫星，此后数年发射了Cartosat-2系列卫星，分辨率达到0.8米。</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://www.caecc.com/index.asp?modelname=gwhtxxi0%5Fnr&amp;FractionNo=&amp;titleno=gwhtxxi0&amp;recno=1471">http://www.caecc.com/index.asp?modelname=gwhtxxi0%5Fnr&amp;FractionNo=&amp;titleno=gwhtxxi0&amp;recno=1471</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='litpic'}{/dede:field}
