<?php
$z[0]=Array("noteinfo","",0,222);
$z[0][4]['notename']="采集测试";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://www.radi.cas.cn/dtxw/qysm/201408/t20140822_4190266.html";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}http://www.radi.cas.cn/dtxw/qysm/index.html{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<td><table cellspacing=\"1\" cellpadding=\"0\" width=\"100%\" align=\"center\" border=\"0\">{/dede:areastart}\r\n    {dede:areaend}<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">{/dede:areaend}\r\n",224,838);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.radi.cas.cn/dtxw/qysm/index_(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="3";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']=".html";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>