{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}FEMA报告指出气候变化可能使洪灾风险增加54%</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: justify">根据美国联邦应急管理局（Federal Emergency Management Agency，FEMA）在2013年6月发布的报告，由于海平面上升和日益严峻的天气变化，到2010年，美国受到洪灾风险的区域将增长至45%。报告题为《2100年气候变化与人口增长对国家洪灾保险计划的影响》（The Impact of Climate Change and Population Growth on the National Flood Insurance Programthrough 2100），这是FEMA首次发布此类报告，该报告指出，这些变化可能使国家洪灾保险计划（National Flood Insurance Program，NFIP）中的易发洪灾财产数量增加一倍，这将大大增加了洪灾的成本。</P>
<P style="TEXT-ALIGN: justify">该报告指出，气候变化可能会极大程度地扩大并增加为期45年的国家洪灾保险计划的规模与成本。之前的政府报告称，到本世纪末，预计海平面将平均上升4英尺。但最新的动态是，到本世纪末，美国处于洪灾风险中的区域将增长至40%~45%之间，这包括沿海地区以及河流沿岸。这种转变会给洪灾保险计划一个重击。在2009年，该计划支出的保险费用总额为32亿美元，到2040年，这一数字将增长至54亿美元，而到2100年，这一数字更将高达112亿美元。这份长达257页的报告历时近五年的研究时间，在经过气候服务台（Climate Desk）<A class=" FCK__AnchorC" title="" href="http://10.0.3.150/wcm/WCMV6/editor/editor/fckeditor.html?InstanceName=TRS_Editor&amp;Toolbar=WCM6&amp;Version=1.0.0.1&amp;ConfigEx=fckconfig_ex.js#_ftn1" name=_ftnref1 _fcksavedurl="http://10.0.3.150/wcm/WCMV6/editor/editor/fckeditor.html?InstanceName=TRS_Editor&amp;Toolbar=WCM6&amp;Version=1.0.0.1&amp;ConfigEx=fckconfig_ex.js#_ftn1">*</A>与琼斯夫人（Mother Jones）等平台与机构的多番咨询基础上，最终由FEMA基础上发布。</P>
<P style="TEXT-ALIGN: justify">这份报告认为，增加的洪灾风险中，只有30%是由人口增长而导致的，而70%是由于气候变化造成的。FEMA划定了被称为特殊洪灾区域的地区，这种地区在任何一年当中，都有1%的概率出现大洪灾（也被称为100年一遇的洪泛平原。）如果有人的家庭有联邦政府支持的抵押贷款且其家正好处于特殊的洪灾区域，那么此家人必须依法购买洪水灾害保险。该报告称，截至2013，国家洪灾保险计划保险的财产为560万美元，但到2100年，这个数字将翻一番，多达1120万美元。</P>
<P style="TEXT-ALIGN: justify">不得不保险财产的2倍对于国家洪灾保险计划而言是一个大问题。它也要像其他保险计划一样运转，当损失发生时，利用投保人每年支付的保险费来弥补损失。但该保险计划在过去十年的大风暴中受到了重创。卡特丽娜飓风后，NFIP的债务达到了160亿美元，在飓风桑迪后，更达到了250亿美元的债务，这些债务可能会无法偿还。该报告预计称，到2100年，平均每笔财产保险的损失可能会增加90%多。如果未来风暴中的受害者不能自己承担损失，那么这部分损失将会由纳税人承担。</P>
<P style="TEXT-ALIGN: justify">FEMA的研究是基于在未来86年内，海平面上升4英尺这样的假设基础上的。但是，美国国家海洋和大气管理局（NOAA）2012年发布的一份报告指出，海平面上升可能会超过6英尺。但无论是4英尺还是6英尺，海平面上升将导致海岸侵蚀和后退，在大风暴事件中将会出现更大的风险。FEMA的报告还指出，在全球变暖的气候条件下，由于降水频率和强度的变化，河流的洪水灾害将会更加严重。报告同时指出，由于人口的增长，从而导致铺砌区域的增加、径流模式和排水系统的改变，这将会对河流洪水发生的数量产生影响。</P>
<P style="TEXT-ALIGN: justify">FEMA的调查结果给这个已经负债累累的保险计划以及美国政府最大的财政负债之一蒙上了一层阴影。气候变化的成本预测表明，要使得该保险计划在财政上健全的可能性不大，除非有重大改变。该报告警告说，国家洪灾保险计划的未来赔付可能远超过其目前的资金和贷款结构能力。</P>
<P style="TEXT-ALIGN: justify">虽然气候变化一直都很惹人注目，但在制定FEMA的预测时并不显眼。然而，此次报告却发现，气候变化是洪灾风险增加的主要驱动力，因此FEMA应该开始考虑气候变化因素，并由此绘制地图，突出高危地区，以应对未来的洪水。</P>
<P style="TEXT-ALIGN: justify">不管是对于联邦政府还是投保个人来讲，气候变化将可能使洪灾保险的费用更加高昂。目前，许多得到联邦政府洪灾保险赔付的房屋屋主需要支付补贴费用。FEMA指出，为了使这个保险计划维持偿还能力，平均每笔保险单的价格将需增长70%来弥补预计的损失。这意味着，目前平均每年支付560美元的个人投保人，到2100年时，不得不每年支付高达952美元的保险费用。</P>
<P style="TEXT-ALIGN: justify">该报告最后经由美国工程设计咨询公司（AECOM）整合，AECOM指出，该报告主要提供的是领域范畴的研究而非系列政策建议。其目的是提供更为精密的研究基础，促进气候变化科学的不断发展。</P>
<HR align=left width="33%" SIZE=1>

<P> </P>
<DIV id=ftn1>
<P style="TEXT-ALIGN: justify"><A class=" FCK__AnchorC" title="" href="http://10.0.3.150/wcm/WCMV6/editor/editor/fckeditor.html?InstanceName=TRS_Editor&amp;Toolbar=WCM6&amp;Version=1.0.0.1&amp;ConfigEx=fckconfig_ex.js#_ftnref1" name=_ftn1 _fcksavedurl="http://10.0.3.150/wcm/WCMV6/editor/editor/fckeditor.html?InstanceName=TRS_Editor&amp;Toolbar=WCM6&amp;Version=1.0.0.1&amp;ConfigEx=fckconfig_ex.js#_ftnref1">*</A>编译注：气候服务台（Climate Desk）是新闻界的一种联合协作，致力于探索气候变化对人类、环境、经济与政治的影响。其成员由《大西洋月报》（The Atlantic）、《调查性报道中心》 （Center for Investigative Reporting）、《卫报》（The Guardian）、 Grist杂志（环境问题是Grist杂志的焦点）、《琼斯夫人》杂志（Mother Jones）、Slate杂志（美国时政漫画杂志）、《连线》杂志（Wired） 及美国公共电视网（PBS）的Need To Know等组成。目标是尝试一种分散的媒体协作模式，即组织一群分散的报道队伍，共同头脑风暴、分配任务并且分享报道。目前的资金来源主要是苏德纳基金会（Surdna Foundation）和帕克基金（Park Foundation）两家一直支持环境类新闻的基金会，同时，罗森塔尔家庭基金（Rosenthal Family Foundation）也给予资金支持。它的运作由来自于各个合作伙伴的编辑记者们协作完成。详见http://climatedesk.org.</P></DIV>
<P style="TEXT-ALIGN: justify">&nbsp;</P>
<P style="TEXT-ALIGN: justify">原文题目：</P>
<P style="TEXT-ALIGN: justify">The Impact of Climate Change and Population Growth on the National Flood Insurance Program through 2100</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://www.aecom.com/News/Sustainability/FEMA+Climate+Change+Report">http://www.aecom.com/News/Sustainability/FEMA+Climate+Change+Report</A></P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='litpic'}{/dede:field}
