{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}美2017年开展类地行星探测新计划</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: justify">美国宇航局（NASA）计划于2017年发射一枚类地行星探测卫星，以及一部用来研究中子星的太空设备。这两项小型探测任务很有可能对天体物理学研究产生巨大影响。</P>
<P style="TEXT-ALIGN: justify">凌日行星勘测卫星（TESS）的目标旨在寻找周围恒星适宜人类居住区域内的类地行星。该卫星将使用大量广角照相机来捕捉太阳附近最亮的恒星，从而希望能够找到系外类地行星，例如气态巨行星或地球大小的岩体行星。研究人员希望，其中的一些系外行星能够成为随后由詹姆斯韦伯太空望远镜展开的行星大气研究的候选者——该望远镜计划于2018年发射升空。</P>
<P style="TEXT-ALIGN: justify">NASA选择的另一项太空任务则是中子星内部构成探测器（NICER），它将被部署于国际空间站内。这架探测器将用来观测由中子星释放出的X射线，从而帮助研究人员了解这些由大质量恒星塌缩后形成的致密旋转天体的构成本质。</P>
<P style="TEXT-ALIGN: justify">这项任务的首席研究者、剑桥市麻省理工学院（MIT）的高级研究员George Ricker在一份声明中表示：“TESS将进行首次以空间方式负载的全天凌日调查，其覆盖的天空将达到之前任何任务的400倍。”Ricker说：“它将发现位于恒星周围的数以千计的新行星，并将特别着重于那些大小与地球类似的行星。”</P>
<P style="TEXT-ALIGN: justify">而之前的CoRoT和开普勒探测器则存在更多观测区域上的限制。Ricker表示：“通常来说，TESS与目标恒星的距离仅仅是开普勒与目标恒星距离的1/10。”这意味着TESS的恒星要比开普勒的恒星亮得多，并且也更容易得到一些有意义的发现。</P>
<P style="TEXT-ALIGN: justify">相对于开普勒望远镜的400到850毫微米波长，安置在TESS上的照相机在600至1050毫微米波长上的灵敏性会更高。Ricker表示，这使得TESS有更好的机会发现位于温度较低的恒星周围的岩体行星。</P>
<P style="TEXT-ALIGN: center"><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/./W020130423496937982990.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130423496679597662.jpg" OLDSRC=W020130423496937982990.jpg></P>
<P style="TEXT-ALIGN: justify">TESS和NICER都被选为NASA的“天体物理学探测器”计划的一部分，它们源自去年秋天提交给该局的4个概念性研究。TESS将耗资2亿美元，而NICER——由马里兰州绿地市NASA戈达德空间飞行中心的Keith Gendreau主持——将获得5500万美元的资金。</P>
<P style="TEXT-ALIGN: justify">类地行星是指以硅酸盐岩石为主要成分的行星。类地行星与气体巨星有极大的不同，气体巨星可能没有固体的表面，而主要的成分是氢、氦和存在不同物理状态下的水。而类地行星主要包含一个由铁构成的金属中心，外层则被硅酸盐地幔所包围。它们的表面一般都有峡谷、陨石坑、山和火山。</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://www.stdaily.com/stdaily/content/2013-04/12/content_592461.htm">http://www.stdaily.com/stdaily/content/2013-04/12/content_592461.htm</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
