{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}USGS发布《自然灾害响应》报告</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: justify">2012年12月16日，美国地质调查局（USGS）发布《自然灾害响应》报告（USGSNaturalHazardsResponse），提出了自然灾害响应的主要目标是确保在紧急事件期间和之后社会对灾害响应获得及时、准确和相关的地理信息产品、图像和服务。</P>
<P style="TEXT-ALIGN: justify">为了实现这一目标，美国国家地理空间计划（NGP）和土地遥感（LRS）计划作为一个地理空间框架对社区紧急响应的测绘活动提供产品和服务。灾后影像和分析可以提供重要和及时的受灾范围和程度信息。USGS自然灾害响应也将支持遥感数据采集和图像分发，权威地理空间信息产品用于备灾、救灾和灾后恢复所需。</P>
<P style="TEXT-ALIGN: justify"><STRONG>1 &nbsp;USGS自然灾害响应的产品和服务</STRONG></P>
<P style="TEXT-ALIGN: justify">当灾难袭来时，往往灾前和灾后地理信息产品、服务和图像的快速采集和协调分发是迫切需要的。这些产品和服务都需要记录变化，分析影响，并促进对地面高度动态状况的响应。</P>
<P style="TEXT-ALIGN: justify">因为地理空间技术的不断推进和支持紧急救援人员的扩大，及时提供相关的数据集变得尤其重要。</P>
<P style="TEXT-ALIGN: justify">根据要求，USGS对自然灾害响应可提供以下支持：（1）采集和协调遥感影像（卫星和航空影像）。（2）提供灾前和灾后卫星和航空影像数据网站。（3）根据需要协调联邦、州和地方应急机构。（4）提供及时有效的影像和地理空间分析。（5）USGS地理空间专家提供快速部署和服务，包括科学响应车辆（SRV）的现场部署。（6）通过《空间与重大灾害国际宪章》提供美国的应对灾害表现、事件反应和事件支持。</P>
<P style="TEXT-ALIGN: center"><STRONG><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/./W020130411487697831379.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130114354130385857.jpg" OLDSRC=W020130411487697831379.jpg /></STRONG></P>
<P style="TEXT-ALIGN: center"><STRONG>USGS Hazards Data Distribution System (HDDS)</STRONG></P>
<P style="TEXT-ALIGN: justify"><STRONG>2&nbsp; USGS应对过去突发事件的经验</STRONG></P>
<P style="TEXT-ALIGN: justify">在过去的十年中，USGS自然灾害响应工作人员都为数以百计的国内和国际灾害事件提供急需的灾前和灾后地理空间产品、遥感影像以及其他相关的空间信息服务。全国最大的事件响应由USGS支持，包括2005年卡特里娜飓风和2010年深水地平线石油泄漏事件。除了这些非常大的复杂的持续时间长的事件，USGS还支持许多其他紧急事件，如2011年德克萨斯州和美国西南地区持久性的危险野火、美国东南部毁灭性的龙卷风、飓风艾琳造成的横跨大西洋中部和新英格兰洪水灾害、密西西比河和密苏里河长期的洪水。USGS也支持国际事件，包括2010年海地大地震，2011年日本地震、海啸及核辐射事件，以及2010年巴基斯坦洪水灾害。</P>
<P style="TEXT-ALIGN: center"><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/./W020130411487698063782.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130114354405023693.jpg" OLDSRC=W020130411487698063782.jpg /><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/./W020130411487698162895.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130114354506301720.jpg" OLDSRC=W020130411487698162895.jpg /></P>
<P style="TEXT-ALIGN: center"><STRONG>图1 &nbsp;截止2012年10月，HDDS所支持的灾害事件类型和可访问的数据集</STRONG></P>
<P style="TEXT-ALIGN: justify"></P>
<P style="TEXT-ALIGN: justify"><STRONG>3&nbsp; 灾害前后地理空间信息的访问</STRONG></P>
<P style="TEXT-ALIGN: justify">当发生紧急情况时，第一反应者和灾害响应团队经常需要快速访问航空摄影和卫星图像，立即获得灾害信息。搭配防治图像，所得到的产品可以方便评估变化，为响应人员提供关键信息。USGS的灾害数据分布系统（HDDS）为应急响应和灾后恢复提供了必不可少的对遥感影像和地理空间数据集以支持方便快捷的访问。</P>
<P style="TEXT-ALIGN: justify"><STRONG>4 &nbsp;灾害数据分布系统</STRONG></P>
<P style="TEXT-ALIGN: justify">HDDS对于访问USGS主办的所有可用的相关紧急事件响应数据集（见图1）提供一个单一的、综合的入口点和分布系统。HDDS提供数据可视性和立即下载服务，通过一对互补的图形化地图为基础，以传统的基于目录为接口。这些接口使得应急响应人员快速选择并获得事件前后的应急响应图像。</P>
<P style="TEXT-ALIGN: justify">基于地图互动HDDS接口的功能包括：（1）即时下载事件有关的影像；（2）影像浏览和覆盖区域的地理数据可视化；（3）多种格式的广泛元数据（例如，KML，CSV，XML，SHP，FGDC）；（4）为基于XML的聚合内容（RSS）提供获取的新数据；（5）服务注册和登录访问受限制的数据集；（6）大量数据的下载能力。</P>
<P style="TEXT-ALIGN: justify">自2005年成立以来，USGS的HDDS系统已经发展超过170 TB级应急响应数据集（相当于超过700个基准和灾害事件）和为应急响应社区分发了大约300万份文件。</P>
<P style="TEXT-ALIGN: justify">原文题目：United States Geological Survey (USGS) Natural Hazards Response</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://pubs.er.usgs.gov/publication/fs20123061">http://pubs.er.usgs.gov/publication/fs20123061</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
