<?php
$z[0]=Array("addurls","http://www.radi.cas.cn/dtxw/qysm/index.html",6,78);
$z[1]=Array("batchrule","",84,117);
$z[2]=Array("regxrule","",123,154);
$z[3]=Array("areastart","<td><table cellspacing=\"1\" cellpadding=\"0\" width=\"100%\" align=\"center\" border=\"0\">",160,275);
$z[4]=Array("areaend","<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">",281,388);

?>