{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}美国开展卫星地表空气污染探测实验</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: justify">根据NASA网站2013年1月10日报告，美国NASA与大学合作实施五年3000万美元的DISCOVER-AQ计划。DISCOVER-AQ利用飞机和地面监测点进行空气污染测量，科学实验将载荷空气污染测量科学仪器，采用高空飞机、低空飞机和地面测量相结合的方法，以帮助科学家更好地了解未来如何从空间“看”到地表空气的污染，更有效地观察地表空间的空气污染，做出更好的空气质量预报和更准确地确定污染的来源和各不相同的排放量。</P>
<P style="TEXT-ALIGN: center"><STRONG><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/http://www.radi.ac.cn/dtxw/qysm/201304W020130411487702251301.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130122335205775204.jpg" OLDSRC=W020130411487702251301.jpg><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/http://www.radi.ac.cn/dtxw/qysm/201304W020130411487702472591.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130122335327895860.jpg" OLDSRC=W020130411487702472591.jpg></STRONG></P>
<P style="TEXT-ALIGN: center"><STRONG>左图高空和低空航空遥感飞机设计航迹，右图地表空气状况图。</STRONG></P>
<P style="TEXT-ALIGN: justify">资料来源:</P>
<P style="TEXT-ALIGN: justify"><A href="http://www.nasa.gov/topics/earth/index.html">http://www.nasa.gov/topics/earth/index.html</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
