{dede:noteinfo notename="采集测试" channelid="1" macthtype="string"
    refurl="http://www.radi.cas.cn/dtxw/qysm/201408/t20140822_4190266.html" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.radi.cas.cn/dtxw/qysm/index_(*).html"
startid="1" endid="3" addv="1" urlrule="area" musthas=".html"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<td><table cellspacing="1" cellpadding="0" width="100%" align="center" border="0">{/dede:areastart}
    {dede:areaend}<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">{/dede:areaend}
{/dede:listrule}
