{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}美国集成海洋观测系统计划进展介绍</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: justify"><STRONG>一个集成的海洋观测系统，能够使美国国家海洋与大气管理局（NOAA）及其合作者，为国家提供服务，进而改善生态系统和气候系统；能够持续利用海洋资源，提高公共健康与安全；减少自然灾害和环境改变的影响；增强海洋商业及运输。</STRONG></P>
<P style="TEXT-ALIGN: center"><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/201307/W020130709332789956215.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130709331628744976.jpg" OLDSRC=W020130709332789956215.jpg></P>
<P style="TEXT-ALIGN: justify"><BR clear=all></P>
<P style="TEXT-ALIGN: justify"><A class=" FCK__AnchorC" name=OLE_LINK9>美国集成海洋观测系统（</A><SPAN>U.S. IOOS</SPAN>）引领海洋、海岸和五大湖观测能力，连接政府和非政府合作者。最大化地获取数据和信息产品，促进决策，提高国家和社会的经济、环境和社会利益。在过去几年的事件中，包括桑迪飓风事件和深水“地平线”石油钻井平台泄漏事件，已经唤起了美国对海洋信息及时性的价值和重要性的关注。海洋观测委员会（IOOC）建议U.S. IOOS响应和支持国家中的这些事件，以及支持国家海洋经济。</P>
<P style="TEXT-ALIGN: justify">美国有最大的高频雷达网络提供海洋表面实时信息，在桑迪和艾琳飓风期间，提供了非常有价值的信息。支持对地观测，自主滑翔机和浮标现在常规的配置，提高对地下海洋环境的认识，在一些区域，提供高达90%的观测。</P>
<P style="TEXT-ALIGN: justify">U.S. IOOS努力协调从全球到区域尺度的海洋模式。在全球尺度上，全球实时海洋预警系统的海洋模型是NOAA大型国家海洋建模核心能力的构成部分。在区域尺度上，<A class=" FCK__AnchorC" name=OLE_LINK7>U.S. IOOS</A>加利福尼亚区域协会联合起来采用一个全州的海洋模 <BR clear=all>式。</P>
<P style="TEXT-ALIGN: center"><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/201307/W020130709332789962108.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130709331868485322.jpg" OLDSRC=W020130709332789962108.jpg></P>
<P style="TEXT-ALIGN: justify">U.S. IOOS应用的成功案例证明了其存在的价值。它实现了一个完全的海洋观测系统的能力，依赖于联邦机构、区域协会、联合产业共同提供集成数据和信息向使用者，对国家的产业经济、社会及环境产生了极好效益。</P>
<P style="TEXT-ALIGN: justify">&nbsp;</P>
<P style="TEXT-ALIGN: justify">原文题目：U.S. Integrated Ocean Observing System&nbsp;(U.S. IOOS) 2013 Report to Congress</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://http://www.ioos.noaa.gov/about/governance/">http://http://www.ioos.noaa.gov/about/governance/</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='litpic'}{/dede:field}
