{dede:field name='keywords'}遥感与数字地球、数字地{/dede:field}
{dede:field name='description'}中国科学院遥感与数字地球研究所,目前拥有遥感科学国家重点实验室、国家航天局航天遥感论证中心、国家遥感应用工程技术研究中心、遥感卫星应用国家工程实验室四大国家级科研机{/dede:field}
{dede:field name='title'}法拟绘制三维数字国土地图，将地表及地下大量信息纳入其中</strong>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<DIV class=cas_content>
<P style="TEXT-ALIGN: justify">据法国《世界报》报道，法国地质矿业研究局（BRGM）计划实施一项浩大工程——绘制法国三维数字国土地图，其内容将涵盖法国本土所有地区及海外省的地表及地下三维地质构造、地热、地下水等信息。该项目将动员数千研究人员和学者，整个周期预计耗时30年，目前评估的总成本达3亿欧元。该计划如能完成，这一3D地图不仅能为研究人员进行地质科研提供帮助，还能够为工业家、地方政府和开发商提供丰富的地下能源资源信息和地质灾害风险评估。</P>
<P style="TEXT-ALIGN: justify">BRGM地质资源主任让-克洛德·吉朗诺表示，绘制3D地图这一长期计划眼下并非从零开始。法国自上世纪70年代至今绘制了多达1064张高分辨率地质图，建立了世界领先的地质信息数据库。然而，这些二维地图仅能描述地表情况，在这些地质资料基础上，富有开拓精神的法国地质学家决心建立3D数字地图，将地上与深及2公里的地下世界绘制成统一的三维模型地图，并将大量地下信息纳入其中。</P>
<P style="TEXT-ALIGN: center"><IMG style="BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px" src="http://www.radi.cas.cn/dtxw/qysm/201307/W020130718502688089001.jpg" _fcksavedurl="/wcm/WCMV6/system/read_image.jsp?FileName=U020130718502470702552.jpg" OLDSRC=W020130718502688089001.jpg></P>
<P style="TEXT-ALIGN: justify"><BR clear=all>　 为了绘制法国的地下世界，BRGM将利用约70万个钻井数十年来探测并建立的地下数据库，这些钻井包括浅层水井、地热井及约6000个深层石油、天然气井。此外，地下测绘还将利用法国石油勘探企业、417000个重力台站（观测重力及地质环境变化）及飞机勘测的地质数据。</P>
<P style="TEXT-ALIGN: justify">大量地质信息组成了庞大的数据库，在此基础上建立三维地质模型还需要对数据进一步的处理和协调利用，BRGM联合德国和瑞士的研究团队，已针对两个试点地区的地热情况进行了绘制。下一步计划将于2014年启动，在5年时间内对比利牛斯山脉进行测绘。之后将逐步展开工作范围，直至整个法国国土绘制完成。</P>
<P style="TEXT-ALIGN: justify">项目完成后，预期能够发挥多方面作用。首先，3D国土地图将更清晰地反映地下水资源、矿藏和能源的储备分布情况，利于开发；其次，能帮助人们找到可用的地下储藏岩洞，用以填埋二氧化碳，贮藏水、石油或其他物资，建设隧道等；此外，还可加强对洪水、地震等自然灾害的评估能力。法国BRGM绘制3D地图不仅将服务于研究机构和公共部门，还将对私营企业和社会大众开放，从而为法国全面开拓地下疆土、发展经济注入新的动力。</P>
<P style="TEXT-ALIGN: justify">来源：</P>
<P style="TEXT-ALIGN: justify"><A href="http://www.stdaily.com/stdaily/content/2013-07/10/content_622450.htm">http://www.stdaily.com/stdaily/content/2013-07/10/content_622450.htm</A> </P>
<P style="TEXT-ALIGN: justify">{/dede:field}
{dede:field name='litpic'}{/dede:field}
