<?php
$z[0]=Array("global","",234,266);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",334,366);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",488,520);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",670,702);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",822,854);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("sql"," \r\n        <li><a href='/plus/list.php?tid=[field:id/]'><span>[field:typename/]</span></a></li>\r\n        ",1298,1497);
$z[5][4]['sql']="select * from cbblab_arctype where reid=2 ORDER BY id ASC LIMIT 7;";

?>