<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.radi.cas.cn/dtxw/qysm/./201401/t20140120_4025451.html",61,160);
$z[2]=Array("keywordtrim","",162,199);
$z[3]=Array("descriptiontrim","",201,246);
$z[4]=Array("item","\r\n   {dede:match}<td height=\"41\" align=\"center\" class=\"hong1\"><strong>[内容]</td>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",248,453);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",453,593);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",593,733);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",733,874);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<td class=\"nrhei\">[内容]资料提供{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",874,1052);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>