<?php
$z[0]=Array("global","",234,266);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",334,366);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",472,504);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",652,684);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",804,836);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1366,1391);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n        <li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n        ",1437,1599);
$z[6][4]['reid']="26";
$z[6][4]['type']="son";
$z[6][4]['row']="8";
$z[7]=Array("sql"," \r\n        <li><a href='/plus/list.php?tid=[field:id/]'><span>[field:typename/]</span></a></li>\r\n        ",1614,1814);
$z[7][4]['sql']="select * from cbblab_arctype where reid=1 ORDER BY id ASC LIMIT 8 ;";

?>